name = "GaussianRandomVariables"
uuid = "dc8732e6-f4b5-4f59-a2b3-73aaa378a5c6"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
ThickNumbers = "b57aa878-5b76-4266-befc-f8e007760995"

[compat]
SpecialFunctions = "2"
ThickNumbers = "1"
julia = "1"

[extras]
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["HypothesisTests", "Test"]
